source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'TestOC' do
	pod 'AFNetworking', '~> 2.6.3’
	pod 'Masonry'
	pod 'Toast', '~> 3.1.0'
	pod 'JSONModel'
	pod 'SDWebImage', '~>3.8'
end